[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
soltip = "BhynwWdN5g5S5FfCEgDovajaYQDq925S2Xs8vXas58uo"

[programs.devnet]
soltip = "BhynwWdN5g5S5FfCEgDovajaYQDq925S2Xs8vXas58uo"

[programs.mainnet-beta]
soltip = "BhynwWdN5g5S5FfCEgDovajaYQDq925S2Xs8vXas58uo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
